//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKkutuGui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiI18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiI18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoKkutuGui.GuiI18n", typeof(GuiI18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to AllocConsole() : Error code {0}.
        /// </summary>
        public static string AllocConsoleFailed {
            get {
                return ResourceManager.GetString("AllocConsoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mode enabled, but can&apos;t find any path..
        /// </summary>
        public static string Auto_NoMorePathAvailable {
            get {
                return ResourceManager.GetString("Auto_NoMorePathAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mode enabled, found path, but there&apos;s no word submittable in time..
        /// </summary>
        public static string Auto_TimeOver {
            get {
                return ResourceManager.GetString("Auto_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a game finished.
        /// </summary>
        public static string AutoDBUpdate_OnGameEnd {
            get {
                return ResourceManager.GetString("AutoDBUpdate_OnGameEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a round finished.
        /// </summary>
        public static string AutoDBUpdate_OnRoundEnd {
            get {
                return ResourceManager.GetString("AutoDBUpdate_OnRoundEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding {word} in kkutu dictionary....
        /// </summary>
        public static string BatchJob_CheckOnline {
            get {
                return ResourceManager.GetString("BatchJob_CheckOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Find {word} in kkutu dict..
        /// </summary>
        public static string BatchJob_CheckOnline_Found {
            get {
                return ResourceManager.GetString("BatchJob_CheckOnline_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaild server response. Resend the request..
        /// </summary>
        public static string BatchJob_CheckOnline_InvalidResponse {
            get {
                return ResourceManager.GetString("BatchJob_CheckOnline_InvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find {word} in kkutu dict..
        /// </summary>
        public static string BatchJob_CheckOnline_NotFound {
            get {
                return ResourceManager.GetString("BatchJob_CheckOnline_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Response : {response}.
        /// </summary>
        public static string BatchJob_CheckOnline_Response {
            get {
                return ResourceManager.GetString("BatchJob_CheckOnline_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging console enabled where debugging is not enabled.
        /// </summary>
        public static string ConsoleIntroduction {
            get {
                return ResourceManager.GetString("ConsoleIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to call console DeleteMenu() : Error code {0}.
        /// </summary>
        public static string DeleteConsoleMenuFailed {
            get {
                return ResourceManager.GetString("DeleteConsoleMenuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All words.
        /// </summary>
        public static string GameMode_All {
            get {
                return ResourceManager.GetString("GameMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and Last.
        /// </summary>
        public static string GameMode_FirstAndLast {
            get {
                return ResourceManager.GetString("GameMode_FirstAndLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string GameMode_Free {
            get {
                return ResourceManager.GetString("GameMode_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kkutu.
        /// </summary>
        public static string GameMode_Kkutu {
            get {
                return ResourceManager.GetString("GameMode_Kkutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KungKungTta.
        /// </summary>
        public static string GameMode_KungKungTta {
            get {
                return ResourceManager.GetString("GameMode_KungKungTta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last and First.
        /// </summary>
        public static string GameMode_LastAndFirst {
            get {
                return ResourceManager.GetString("GameMode_LastAndFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Last and First.
        /// </summary>
        public static string GameMode_LastAndFirstFree {
            get {
                return ResourceManager.GetString("GameMode_LastAndFirstFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle and First.
        /// </summary>
        public static string GameMode_MiddleAndFirst {
            get {
                return ResourceManager.GetString("GameMode_MiddleAndFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing battle.
        /// </summary>
        public static string GameMode_TypingBattle {
            get {
                return ResourceManager.GetString("GameMode_TypingBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered previous handler: {0}.
        /// </summary>
        public static string HandlerRegistry_Unregistered {
            get {
                return ResourceManager.GetString("HandlerRegistry_Unregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-entering path: {word}.
        /// </summary>
        public static string Main_AutoEnter {
            get {
                return ResourceManager.GetString("Main_AutoEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser frame-load end..
        /// </summary>
        public static string Main_CEFFrameLoadEnd {
            get {
                return ResourceManager.GetString("Main_CEFFrameLoadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t submit clipboard text..
        /// </summary>
        public static string Main_ClipboardSubmitException {
            get {
                return ResourceManager.GetString("Main_ClipboardSubmitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing database connection....
        /// </summary>
        public static string Main_ClosingDBConnection {
            get {
                return ResourceManager.GetString("Main_ClosingDBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated color preferences..
        /// </summary>
        public static string Main_ColorPrefsUpdated {
            get {
                return ResourceManager.GetString("Main_ColorPrefsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configurations..
        /// </summary>
        public static string Main_ConfigLoadException {
            get {
                return ResourceManager.GetString("Main_ConfigLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated configurations..
        /// </summary>
        public static string Main_ConfigUpdated {
            get {
                return ResourceManager.GetString("Main_ConfigUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading database.config.
        /// </summary>
        public static string Main_DBConfigException {
            get {
                return ResourceManager.GetString("Main_DBConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically updated game mode to {gameMode}.
        /// </summary>
        public static string Main_GameModeUpdated {
            get {
                return ResourceManager.GetString("Main_GameModeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write game result..
        /// </summary>
        public static string Main_GameResultWriteException {
            get {
                return ResourceManager.GetString("Main_GameResultWriteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} initialization took {1}ms..
        /// </summary>
        public static string Main_Initialization {
            get {
                return ResourceManager.GetString("Main_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulating {attr:l} word input: {word}.
        /// </summary>
        public static string Main_InputSimulating {
            get {
                return ResourceManager.GetString("Main_InputSimulating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input simulation of {attr:l} word aborted: {words}.
        /// </summary>
        public static string Main_InputSimulationAborted {
            get {
                return ResourceManager.GetString("Main_InputSimulationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input simulation of {attr:l} word finished: {word}.
        /// </summary>
        public static string Main_InputSimulationFinished {
            get {
                return ResourceManager.GetString("Main_InputSimulationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My path {word} was confirmed unsupported..
        /// </summary>
        public static string Main_MyPathIsUnsupported {
            get {
                return ResourceManager.GetString("Main_MyPathIsUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Main_Next {
            get {
                return ResourceManager.GetString("Main_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no path available..
        /// </summary>
        public static string Main_NoMorePathAvailable {
            get {
                return ResourceManager.GetString("Main_NoMorePathAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optimal.
        /// </summary>
        public static string Main_Optimal {
            get {
                return ResourceManager.GetString("Main_Optimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t submit path due exception..
        /// </summary>
        public static string Main_PathSubmitException {
            get {
                return ResourceManager.GetString("Main_PathSubmitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path submitted: {word}..
        /// </summary>
        public static string Main_PathSubmitted {
            get {
                return ResourceManager.GetString("Main_PathSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path update received..
        /// </summary>
        public static string Main_PathUpdateReceived {
            get {
                return ResourceManager.GetString("Main_PathUpdateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to presented.
        /// </summary>
        public static string Main_Presented {
            get {
                return ResourceManager.GetString("Main_Presented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset path list... .
        /// </summary>
        public static string Main_ResetPathList {
            get {
                return ResourceManager.GetString("Main_ResetPathList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start loading page....
        /// </summary>
        public static string Main_StartLoad {
            get {
                return ResourceManager.GetString("Main_StartLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported site: {url}.
        /// </summary>
        public static string Main_UnsupportedURL {
            get {
                return ResourceManager.GetString("Main_UnsupportedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered word {word} is exists but not supported, added to unsupported list..
        /// </summary>
        public static string Main_UnsupportedWord_Existent {
            get {
                return ResourceManager.GetString("Main_UnsupportedWord_Existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered word {word} is inexistent, added to removal list..
        /// </summary>
        public static string Main_UnsupportedWord_Inexistent {
            get {
                return ResourceManager.GetString("Main_UnsupportedWord_Inexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using handler: {0}.
        /// </summary>
        public static string Main_UseHandler {
            get {
                return ResourceManager.GetString("Main_UseHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}ms before entering path..
        /// </summary>
        public static string Main_WaitingSubmit {
            get {
                return ResourceManager.GetString("Main_WaitingSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}ms before submitting next path..
        /// </summary>
        public static string Main_WaitingSubmitNext {
            get {
                return ResourceManager.GetString("Main_WaitingSubmitNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset WordIndex to zero..
        /// </summary>
        public static string Main_WordIndexReset {
            get {
                return ResourceManager.GetString("Main_WordIndexReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new {0} node &apos;{1}&apos;.
        /// </summary>
        public static string PathFinder_AddNode {
            get {
                return ResourceManager.GetString("PathFinder_AddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check and add {word} into database. (flags: {flags}).
        /// </summary>
        public static string PathFinder_AddPath {
            get {
                return ResourceManager.GetString("PathFinder_AddPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add {word} to database..
        /// </summary>
        public static string PathFinder_AddPath_Failed {
            get {
                return ResourceManager.GetString("PathFinder_AddPath_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {word} into database..
        /// </summary>
        public static string PathFinder_AddPath_Success {
            get {
                return ResourceManager.GetString("PathFinder_AddPath_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically updating the database based on last game..
        /// </summary>
        public static string PathFinder_AutoDBUpdate {
            get {
                return ResourceManager.GetString("PathFinder_AutoDBUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such element in autoupdate list..
        /// </summary>
        public static string PathFinder_AutoDBUpdate_Empty {
            get {
                return ResourceManager.GetString("PathFinder_AutoDBUpdate_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic database update finished: {0}.
        /// </summary>
        public static string PathFinder_AutoDBUpdate_Finished {
            get {
                return ResourceManager.GetString("PathFinder_AutoDBUpdate_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got {0} elements from NewPathList..
        /// </summary>
        public static string PathFinder_AutoDBUpdate_New {
            get {
                return ResourceManager.GetString("PathFinder_AutoDBUpdate_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got {0} elements from WrongPathList..
        /// </summary>
        public static string PathFinder_AutoDBUpdate_Remove {
            get {
                return ResourceManager.GetString("PathFinder_AutoDBUpdate_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} word(s) added, {2} of {3} word(s) removed, {4} of {5} end-node(s) added..
        /// </summary>
        public static string PathFinder_AutoDBUpdate_Result {
            get {
                return ResourceManager.GetString("PathFinder_AutoDBUpdate_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding path for {word}..
        /// </summary>
        public static string PathFinder_FindPath {
            get {
                return ResourceManager.GetString("PathFinder_FindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find path..
        /// </summary>
        public static string PathFinder_FindPath_Error {
            get {
                return ResourceManager.GetString("PathFinder_FindPath_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find any path..
        /// </summary>
        public static string PathFinder_FindPath_NotFound {
            get {
                return ResourceManager.GetString("PathFinder_FindPath_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding path for {word} and {substituation}..
        /// </summary>
        public static string PathFinder_FindPath_Substituation {
            get {
                return ResourceManager.GetString("PathFinder_FindPath_Substituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} words. (AttackWord: {1}, EndWord: {2}).
        /// </summary>
        public static string PathFinder_FoundPath {
            get {
                return ResourceManager.GetString("PathFinder_FoundPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} words are ready. (Took {1}ms).
        /// </summary>
        public static string PathFinder_FoundPath_Ready {
            get {
                return ResourceManager.GetString("PathFinder_FoundPath_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update node lists..
        /// </summary>
        public static string PathFinder_Init_Error {
            get {
                return ResourceManager.GetString("PathFinder_Init_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidated potential incorrect path update result. (Word: {0}, MissionChar: {1}).
        /// </summary>
        public static string PathFinder_InvalidatedUpdate {
            get {
                return ResourceManager.GetString("PathFinder_InvalidatedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete {word} from database..
        /// </summary>
        public static string PathFinder_RemoveInexistent_Failed {
            get {
                return ResourceManager.GetString("PathFinder_RemoveInexistent_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string PathFinderAttackWord {
            get {
                return ResourceManager.GetString("PathFinderAttackWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string PathFinderEndWord {
            get {
                return ResourceManager.GetString("PathFinderEndWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find word due to exception..
        /// </summary>
        public static string PathFinderError {
            get {
                return ResourceManager.GetString("PathFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find any path : Presented word is end word..
        /// </summary>
        public static string PathFinderFailed_Endword {
            get {
                return ResourceManager.GetString("PathFinderFailed_Endword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find path due exception..
        /// </summary>
        public static string PathFinderFailed_Exception {
            get {
                return ResourceManager.GetString("PathFinderFailed_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} total, {1} feasible..
        /// </summary>
        public static string PathFinderFound {
            get {
                return ResourceManager.GetString("PathFinderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found total {0}, but none of them are feasible..
        /// </summary>
        public static string PathFinderFoundButEmpty {
            get {
                return ResourceManager.GetString("PathFinderFoundButEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} word(s) used..
        /// </summary>
        public static string PathFinderIncludedWord {
            get {
                return ResourceManager.GetString("PathFinderIncludedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result for {0}.
        /// </summary>
        public static string PathFinderSearchOverview {
            get {
                return ResourceManager.GetString("PathFinderSearchOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, mission char &apos;{1}&apos;.
        /// </summary>
        public static string PathFinderSearchOverview_MissionChar {
            get {
                return ResourceManager.GetString("PathFinderSearchOverview_MissionChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1}.
        /// </summary>
        public static string PathFinderSearchOverview_Or {
            get {
                return ResourceManager.GetString("PathFinderSearchOverview_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0}ms..
        /// </summary>
        public static string PathFinderTookTime {
            get {
                return ResourceManager.GetString("PathFinderTookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available word found..
        /// </summary>
        public static string PathFinderUnavailable {
            get {
                return ResourceManager.GetString("PathFinderUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string PathFinderWaiting {
            get {
                return ResourceManager.GetString("PathFinderWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node {node} is already marked as {type}. [Gamemode: {gameMode}].
        /// </summary>
        public static string PathMark_AlreadyDone {
            get {
                return ResourceManager.GetString("PathMark_AlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attack word.
        /// </summary>
        public static string PathMark_Attack {
            get {
                return ResourceManager.GetString("PathMark_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end word.
        /// </summary>
        public static string PathMark_End {
            get {
                return ResourceManager.GetString("PathMark_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal word.
        /// </summary>
        public static string PathMark_Normal {
            get {
                return ResourceManager.GetString("PathMark_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully marked node {node} as {type}. [Gamemode: {gameMode}].
        /// </summary>
        public static string PathMark_Success {
            get {
                return ResourceManager.GetString("PathMark_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack word: {0}.
        /// </summary>
        public static string PathTooltip_Attack {
            get {
                return ResourceManager.GetString("PathTooltip_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack mission(x{1}) word: {0}.
        /// </summary>
        public static string PathTooltip_AttackMission {
            get {
                return ResourceManager.GetString("PathTooltip_AttackMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End word: {0}.
        /// </summary>
        public static string PathTooltip_End {
            get {
                return ResourceManager.GetString("PathTooltip_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End mission(x{1}) word: {0}.
        /// </summary>
        public static string PathTooltip_EndMission {
            get {
                return ResourceManager.GetString("PathTooltip_EndMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission(x{1}) word: {0}.
        /// </summary>
        public static string PathTooltip_Mission {
            get {
                return ResourceManager.GetString("PathTooltip_Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word: {0}.
        /// </summary>
        public static string PathTooltip_Normal {
            get {
                return ResourceManager.GetString("PathTooltip_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoKkutu {0} - Next-gen Kkutu-Helper V.
        /// </summary>
        public static string ProgramIntroduction {
            get {
                return ResourceManager.GetString("ProgramIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic database updating..
        /// </summary>
        public static string Status_AutoUpdate {
            get {
                return ResourceManager.GetString("Status_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Time {0}ms &gt;= Word Delay {1}ms.
        /// </summary>
        public static string TimeFilter_Success {
            get {
                return ResourceManager.GetString("TimeFilter_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no word submittable in time! (Turn Time {0}ms).
        /// </summary>
        public static string TimeFilter_TimeOver {
            get {
                return ResourceManager.GetString("TimeFilter_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color preference not set..
        /// </summary>
        public static string Validate_ColorPrefs {
            get {
                return ResourceManager.GetString("Validate_ColorPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config not set..
        /// </summary>
        public static string Validate_Config {
            get {
                return ResourceManager.GetString("Validate_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database command not initialized..
        /// </summary>
        public static string Validate_DatabaseCommand {
            get {
                return ResourceManager.GetString("Validate_DatabaseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection not established..
        /// </summary>
        public static string Validate_DatabaseConnection {
            get {
                return ResourceManager.GetString("Validate_DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database reader not open..
        /// </summary>
        public static string Validate_DatabaseReader {
            get {
                return ResourceManager.GetString("Validate_DatabaseReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler not registered..
        /// </summary>
        public static string Validate_Handler {
            get {
                return ResourceManager.GetString("Validate_Handler", resourceCulture);
            }
        }
    }
}
