//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKkutuGui {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoEnterEnabled {
            get {
                return ((bool)(this["AutoEnterEnabled"]));
            }
            set {
                this["AutoEnterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDBUpdateEnabled {
            get {
                return ((bool)(this["AutoDBUpdateEnabled"]));
            }
            set {
                this["AutoDBUpdateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5;6;4;1;2;0")]
        public global::AutoKkutuLib.WordPreference ActiveWordPreference {
            get {
                return ((global::AutoKkutuLib.WordPreference)(this["ActiveWordPreference"]));
            }
            set {
                this["ActiveWordPreference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::AutoKkutuLib.WordPreference InactiveWordPreference {
            get {
                return ((global::AutoKkutuLib.WordPreference)(this["InactiveWordPreference"]));
            }
            set {
                this["InactiveWordPreference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EndWordEnabled {
            get {
                return ((bool)(this["EndWordEnabled"]));
            }
            set {
                this["EndWordEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AttackWordEnabled {
            get {
                return ((bool)(this["AttackWordEnabled"]));
            }
            set {
                this["AttackWordEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReturnModeEnabled {
            get {
                return ((bool)(this["ReturnModeEnabled"]));
            }
            set {
                this["ReturnModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoFixEnabled {
            get {
                return ((bool)(this["AutoFixEnabled"]));
            }
            set {
                this["AutoFixEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MissionAutoDetectionEnabled {
            get {
                return ((bool)(this["MissionAutoDetectionEnabled"]));
            }
            set {
                this["MissionAutoDetectionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DelayEnabled {
            get {
                return ((bool)(this["DelayEnabled"]));
            }
            set {
                this["DelayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DelayPerCharEnabled {
            get {
                return ((bool)(this["DelayPerCharEnabled"]));
            }
            set {
                this["DelayPerCharEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DelayInMillis {
            get {
                return ((int)(this["DelayInMillis"]));
            }
            set {
                this["DelayInMillis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DelayStartAfterWordEnterEnabled {
            get {
                return ((bool)(this["DelayStartAfterWordEnterEnabled"]));
            }
            set {
                this["DelayStartAfterWordEnterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MaxDisplayedWordCount {
            get {
                return ((int)(this["MaxDisplayedWordCount"]));
            }
            set {
                this["MaxDisplayedWordCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FixDelayEnabled {
            get {
                return ((bool)(this["FixDelayEnabled"]));
            }
            set {
                this["FixDelayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FixDelayPerCharEnabled {
            get {
                return ((bool)(this["FixDelayPerCharEnabled"]));
            }
            set {
                this["FixDelayPerCharEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FixDelayInMillis {
            get {
                return ((int)(this["FixDelayInMillis"]));
            }
            set {
                this["FixDelayInMillis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 17, 0")]
        public global::System.Drawing.Color EndWordColor {
            get {
                return ((global::System.Drawing.Color)(this["EndWordColor"]));
            }
            set {
                this["EndWordColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color AttackWordColor {
            get {
                return ((global::System.Drawing.Color)(this["AttackWordColor"]));
            }
            set {
                this["AttackWordColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 255, 64")]
        public global::System.Drawing.Color MissionWordColor {
            get {
                return ((global::System.Drawing.Color)(this["MissionWordColor"]));
            }
            set {
                this["MissionWordColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 192, 168")]
        public global::System.Drawing.Color EndMissionWordColor {
            get {
                return ((global::System.Drawing.Color)(this["EndMissionWordColor"]));
            }
            set {
                this["EndMissionWordColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 64")]
        public global::System.Drawing.Color AttackMissionWordColor {
            get {
                return ((global::System.Drawing.Color)(this["AttackMissionWordColor"]));
            }
            set {
                this["AttackMissionWordColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InputSimulate {
            get {
                return ((bool)(this["InputSimulate"]));
            }
            set {
                this["InputSimulate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDBWordAddEnabled {
            get {
                return ((bool)(this["AutoDBWordAddEnabled"]));
            }
            set {
                this["AutoDBWordAddEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDBWordRemoveEnabled {
            get {
                return ((bool)(this["AutoDBWordRemoveEnabled"]));
            }
            set {
                this["AutoDBWordRemoveEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDBAddEndEnabled {
            get {
                return ((bool)(this["AutoDBAddEndEnabled"]));
            }
            set {
                this["AutoDBAddEndEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RandomWordSelection {
            get {
                return ((bool)(this["RandomWordSelection"]));
            }
            set {
                this["RandomWordSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RandomWordSelectionCount {
            get {
                return ((int)(this["RandomWordSelectionCount"]));
            }
            set {
                this["RandomWordSelectionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoEnterInputSimulateJavaScriptSendKeys {
            get {
                return ((bool)(this["AutoEnterInputSimulateJavaScriptSendKeys"]));
            }
            set {
                this["AutoEnterInputSimulateJavaScriptSendKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HijackACPackets {
            get {
                return ((bool)(this["HijackACPackets"]));
            }
            set {
                this["HijackACPackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SimulateAntiCheat {
            get {
                return ((bool)(this["SimulateAntiCheat"]));
            }
            set {
                this["SimulateAntiCheat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DetectInputLogging {
            get {
                return ((bool)(this["DetectInputLogging"]));
            }
            set {
                this["DetectInputLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogChatting {
            get {
                return ((bool)(this["LogChatting"]));
            }
            set {
                this["LogChatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelfAntiCheat {
            get {
                return ((bool)(this["SelfAntiCheat"]));
            }
            set {
                this["SelfAntiCheat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int StartDelay {
            get {
                return ((int)(this["StartDelay"]));
            }
            set {
                this["StartDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int StartDelayRandom {
            get {
                return ((int)(this["StartDelayRandom"]));
            }
            set {
                this["StartDelayRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DelayPerChar {
            get {
                return ((int)(this["DelayPerChar"]));
            }
            set {
                this["DelayPerChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DelayPerCharRandom {
            get {
                return ((int)(this["DelayPerCharRandom"]));
            }
            set {
                this["DelayPerCharRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FixStartDelay {
            get {
                return ((int)(this["FixStartDelay"]));
            }
            set {
                this["FixStartDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FixStartDelayRandom {
            get {
                return ((int)(this["FixStartDelayRandom"]));
            }
            set {
                this["FixStartDelayRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FixDelayPerChar {
            get {
                return ((int)(this["FixDelayPerChar"]));
            }
            set {
                this["FixDelayPerChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FixDelayPerCharRandom {
            get {
                return ((int)(this["FixDelayPerCharRandom"]));
            }
            set {
                this["FixDelayPerCharRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OnlySearchOnMyTurn {
            get {
                return ((bool)(this["OnlySearchOnMyTurn"]));
            }
            set {
                this["OnlySearchOnMyTurn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM7")]
        public string ArduinoPort {
            get {
                return ((string)(this["ArduinoPort"]));
            }
            set {
                this["ArduinoPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int ArduinoBaudrate {
            get {
                return ((int)(this["ArduinoBaudrate"]));
            }
            set {
                this["ArduinoBaudrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Win32InputSimulate")]
        public string AutoEnterMode {
            get {
                return ((string)(this["AutoEnterMode"]));
            }
            set {
                this["AutoEnterMode"] = value;
            }
        }
    }
}
