//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKkutu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoKkutu.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to AllocConsole() : Error code {0}.
        /// </summary>
        public static string AllocConsoleFailed {
            get {
                return ResourceManager.GetString("AllocConsoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mode enabled, but can&apos;t find any path..
        /// </summary>
        public static string Auto_NoMorePathAvailable {
            get {
                return ResourceManager.GetString("Auto_NoMorePathAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mode enabled, found path, but there&apos;s no word submittable in time..
        /// </summary>
        public static string Auto_TimeOver {
            get {
                return ResourceManager.GetString("Auto_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging console enabled where debugging is not enabled.
        /// </summary>
        public static string ConsoleIntroduction {
            get {
                return ResourceManager.GetString("ConsoleIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to call console DeleteMenu() : Error code {0}.
        /// </summary>
        public static string DeleteConsoleMenuFailed {
            get {
                return ResourceManager.GetString("DeleteConsoleMenuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered previous handler: {0}.
        /// </summary>
        public static string HandlerRegistry_Unregistered {
            get {
                return ResourceManager.GetString("HandlerRegistry_Unregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mode enabled. automatically use {attr:l} path: {word}.
        /// </summary>
        public static string Main_AutoEnter {
            get {
                return ResourceManager.GetString("Main_AutoEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser frame-load end..
        /// </summary>
        public static string Main_CEFFrameLoadEnd {
            get {
                return ResourceManager.GetString("Main_CEFFrameLoadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t submit clipboard text..
        /// </summary>
        public static string Main_ClipboardSubmitException {
            get {
                return ResourceManager.GetString("Main_ClipboardSubmitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing database connection....
        /// </summary>
        public static string Main_ClosingDBConnection {
            get {
                return ResourceManager.GetString("Main_ClosingDBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated color preferences..
        /// </summary>
        public static string Main_ColorPrefsUpdated {
            get {
                return ResourceManager.GetString("Main_ColorPrefsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configurations..
        /// </summary>
        public static string Main_ConfigLoadException {
            get {
                return ResourceManager.GetString("Main_ConfigLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated configurations..
        /// </summary>
        public static string Main_ConfigUpdated {
            get {
                return ResourceManager.GetString("Main_ConfigUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading database.config.
        /// </summary>
        public static string Main_DBConfigException {
            get {
                return ResourceManager.GetString("Main_DBConfigException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically updated game mode to {gameMode}.
        /// </summary>
        public static string Main_GameModeUpdated {
            get {
                return ResourceManager.GetString("Main_GameModeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write game result..
        /// </summary>
        public static string Main_GameResultWriteException {
            get {
                return ResourceManager.GetString("Main_GameResultWriteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} initialization took {1}ms..
        /// </summary>
        public static string Main_Initialization {
            get {
                return ResourceManager.GetString("Main_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My path {word} was confirmed unsupported..
        /// </summary>
        public static string Main_MyPathIsUnsupported {
            get {
                return ResourceManager.GetString("Main_MyPathIsUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Main_Next {
            get {
                return ResourceManager.GetString("Main_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no path available..
        /// </summary>
        public static string Main_NoMorePathAvailable {
            get {
                return ResourceManager.GetString("Main_NoMorePathAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optimal.
        /// </summary>
        public static string Main_Optimal {
            get {
                return ResourceManager.GetString("Main_Optimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t submit path due exception..
        /// </summary>
        public static string Main_PathSubmitException {
            get {
                return ResourceManager.GetString("Main_PathSubmitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path submitted: {word}..
        /// </summary>
        public static string Main_PathSubmitted {
            get {
                return ResourceManager.GetString("Main_PathSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path update received..
        /// </summary>
        public static string Main_PathUpdateReceived {
            get {
                return ResourceManager.GetString("Main_PathUpdateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to presented.
        /// </summary>
        public static string Main_Presented {
            get {
                return ResourceManager.GetString("Main_Presented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset path list... .
        /// </summary>
        public static string Main_ResetPathList {
            get {
                return ResourceManager.GetString("Main_ResetPathList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start loading page....
        /// </summary>
        public static string Main_StartLoad {
            get {
                return ResourceManager.GetString("Main_StartLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported site: {url}.
        /// </summary>
        public static string Main_UnsupportedURL {
            get {
                return ResourceManager.GetString("Main_UnsupportedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered word {word} is exists but not supported, added to unsupported list..
        /// </summary>
        public static string Main_UnsupportedWord_Existent {
            get {
                return ResourceManager.GetString("Main_UnsupportedWord_Existent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered word {word} is inexistent, added to removal list..
        /// </summary>
        public static string Main_UnsupportedWord_Inexistent {
            get {
                return ResourceManager.GetString("Main_UnsupportedWord_Inexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using handler: {0}.
        /// </summary>
        public static string Main_UseHandler {
            get {
                return ResourceManager.GetString("Main_UseHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}ms before entering path..
        /// </summary>
        public static string Main_WaitingSubmit {
            get {
                return ResourceManager.GetString("Main_WaitingSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0}ms before submitting next path..
        /// </summary>
        public static string Main_WaitingSubmitNext {
            get {
                return ResourceManager.GetString("Main_WaitingSubmitNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset WordIndex to zero..
        /// </summary>
        public static string Main_WordIndexReset {
            get {
                return ResourceManager.GetString("Main_WordIndexReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidated potential incorrect path update result. (Word: {0}, MissionChar: {1}).
        /// </summary>
        public static string PathFinder_InvalidatedUpdate {
            get {
                return ResourceManager.GetString("PathFinder_InvalidatedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string PathFinderAttackWord {
            get {
                return ResourceManager.GetString("PathFinderAttackWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string PathFinderEndWord {
            get {
                return ResourceManager.GetString("PathFinderEndWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find word due to exception..
        /// </summary>
        public static string PathFinderError {
            get {
                return ResourceManager.GetString("PathFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find any path : Presented word is end word..
        /// </summary>
        public static string PathFinderFailed_Endword {
            get {
                return ResourceManager.GetString("PathFinderFailed_Endword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find path due exception..
        /// </summary>
        public static string PathFinderFailed_Exception {
            get {
                return ResourceManager.GetString("PathFinderFailed_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} total, {1} feasible..
        /// </summary>
        public static string PathFinderFound {
            get {
                return ResourceManager.GetString("PathFinderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found total {0}, but none of them are feasible..
        /// </summary>
        public static string PathFinderFoundButEmpty {
            get {
                return ResourceManager.GetString("PathFinderFoundButEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} word(s) used..
        /// </summary>
        public static string PathFinderIncludedWord {
            get {
                return ResourceManager.GetString("PathFinderIncludedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result for {0}.
        /// </summary>
        public static string PathFinderSearchOverview {
            get {
                return ResourceManager.GetString("PathFinderSearchOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, mission char &apos;{1}&apos;.
        /// </summary>
        public static string PathFinderSearchOverview_MissionChar {
            get {
                return ResourceManager.GetString("PathFinderSearchOverview_MissionChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1}.
        /// </summary>
        public static string PathFinderSearchOverview_Or {
            get {
                return ResourceManager.GetString("PathFinderSearchOverview_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took {0}ms..
        /// </summary>
        public static string PathFinderTookTime {
            get {
                return ResourceManager.GetString("PathFinderTookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available word found..
        /// </summary>
        public static string PathFinderUnavailable {
            get {
                return ResourceManager.GetString("PathFinderUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string PathFinderWaiting {
            get {
                return ResourceManager.GetString("PathFinderWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoKkutu v{0} - Kkutu cheat.
        /// </summary>
        public static string ProgramIntroduction {
            get {
                return ResourceManager.GetString("ProgramIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic database updating..
        /// </summary>
        public static string Status_AutoUpdate {
            get {
                return ResourceManager.GetString("Status_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Time {0}ms &gt;= Word Delay {1}ms.
        /// </summary>
        public static string TimeFilter_Success {
            get {
                return ResourceManager.GetString("TimeFilter_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no word submittable in time! (Turn Time {0}ms).
        /// </summary>
        public static string TimeFilter_TimeOver {
            get {
                return ResourceManager.GetString("TimeFilter_TimeOver", resourceCulture);
            }
        }
    }
}
