//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKkutuLib.CefSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoKkutuLib.CefSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* eslint-disable no-proto */
        ////* eslint-disable accessor-pairs */
        ////* eslint-disable no-global-assign */
        ///
        ////* wsHook.js
        /// * https://github.com/skepticfx/wshook
        /// * Reference: http://www.w3.org/TR/2011/WD-websockets-20110419/#websocket
        /// */
        ///
        ///var wsHook = {};
        ///(function () {
        ///  // Mutable MessageEvent.
        ///  // Subclasses MessageEvent and makes data, origin and other MessageEvent properites mutatble.
        ///  function MutableMessageEvent (o) {
        ///    this.bubbles = o.bubbles || false
        ///    this.cancelBubble = o.cance [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wsHook {
            get {
                return ResourceManager.GetString("wsHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(_0xc091ba,_0x391866){var _0x4bb6ec={_0x29f7bc:0x719,_0x34d4e9:&apos;\x21\x48\x78\x37&apos;,_0x232b57:0x82e,_0x2364bc:0x8b4,_0x375e4a:0x7eb,_0x2df6d6:0x7d7,_0x361ebe:&apos;\x6a\x5d\x51\x5a&apos;,_0x4aaf89:0x66b,_0x439f9b:0x7da,_0x20adf4:0x6e3,_0x5d6c55:0x621,_0xdffc7b:&apos;\x49\x52\x4a\x72&apos;,_0x5b4b20:0x4f9,_0x14b83d:0x6b8,_0x9fa9a0:0x6fc,_0x3a8ce0:0x102,_0x10f3d4:0x98,_0x356251:0x70,_0x2bd0c8:0x161,_0x6ccf22:&apos;\x73\x33\x6e\x33&apos;,_0x381473:0xa,_0xd8640f:0xcf,_0x477dc1:0x3f,_0x223d13:0x6e,_0x2a3ca8:&apos;\x67\x30\x21\x33&apos;,_0x4be74 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wsHookObf {
            get {
                return ResourceManager.GetString("wsHookObf", resourceCulture);
            }
        }
    }
}
