//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKkutuLib.Game.DomHandlers.JavaScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoKkutuLib.Game.DomHandlers.JavaScript.Properties.JsResources", typeof(JsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This code is safe both executed on global and in IIFE
        ///
        ///if (!___gameInProgress___) {
        ///    ___gameInProgress___ = function () {
        ///        var s = document.getElementsByClassName(&apos;GameBox Product&apos;)[0]?.style;
        ///        return s != undefined &amp;&amp; (s?.display ? s.display != &apos;none&apos; : s.height != &apos;&apos;);
        ///    }
        ///}
        ///
        ///
        ///if (!___getGameMode___) {
        ///    ___getGameMode___ = function () {
        ///        if (!___roomHeadMode___)
        ///            ___roomHeadMode___ = document.getElementsByClassName(&apos;room-head-mode&apos;)[0];
        ///
        ///        le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string baseHandler {
            get {
                return ResourceManager.GetString("baseHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This code is safe both executed on global and in IIFE
        ///
        ///// 안티 치트가 적용되었다고 하더라도 대부분의 사이트들은 게임 도중에 진짜 채팅창이나 진짜 &apos;전송&apos; 버튼을 바꿔치기 하지 않음.
        ///// 덕분에, 이러한 DOM 요소들을 매 번 계산하여 알아내는 대신 캐싱해 놓고 신나게 우려먹을 수 있음.
        ///
        ///___updateChat___ = function (input) {
        ///    if (!___chatBox___ || !document.getElementById(___chatBox___.id))
        ///        ___chatBox___ = Array.prototype.find.call(document.querySelectorAll(&apos;#Middle&gt;div.ChatBox.Product&gt;div.product-body&gt;input&apos;), e =&gt; ___getComputedStyle___(e).display != &apos;none&apos;);
        ///
        ///    if (___chatBox__ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bypassHandler {
            get {
                return ResourceManager.GetString("bypassHandler", resourceCulture);
            }
        }
    }
}
