//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoKkutuGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoKkutuGui.Properties.GuiResources", typeof(GuiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;themes&gt;
        ///    &lt;theme ordinal=&quot;1&quot; id=&quot;10&quot; name=&quot;가톨릭&quot; /&gt;
        ///    &lt;theme ordinal=&quot;2&quot; id=&quot;20&quot; name=&quot;건설&quot; /&gt;
        ///    &lt;theme ordinal=&quot;3&quot; id=&quot;30&quot; name=&quot;경제&quot; /&gt;
        ///    &lt;theme ordinal=&quot;4&quot; id=&quot;40&quot; name=&quot;고적&quot; /&gt;
        ///    &lt;theme ordinal=&quot;5&quot; id=&quot;50&quot; name=&quot;고유&quot; /&gt;
        ///    &lt;theme ordinal=&quot;6&quot; id=&quot;60&quot; name=&quot;공업&quot; /&gt;
        ///    &lt;theme ordinal=&quot;7&quot; id=&quot;70&quot; name=&quot;광업&quot; /&gt;
        ///    &lt;theme ordinal=&quot;8&quot; id=&quot;80&quot; name=&quot;교육&quot; /&gt;
        ///    &lt;theme ordinal=&quot;9&quot; id=&quot;90&quot; name=&quot;교통&quot; /&gt;
        ///    &lt;theme ordinal=&quot;10&quot; id=&quot;100&quot; name=&quot;군사&quot; /&gt;
        ///    &lt;the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultThemes {
            get {
                return ResourceManager.GetString("DefaultThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- If you messed up with this file and want to restore defaults, just delete and re-run the program. --&gt;
        ///&lt;servers&gt;
        ///    &lt;default&gt;
        ///        &lt;!-- Supported DOM Handlers: BasisHandler, BasicBypassHandler --&gt;
        ///        &lt;domHandler&gt;BasicDomHandler&lt;/domHandler&gt;
        ///
        ///        &lt;!-- Supported WebSocket Handlers: BasicHandler, RioDecodeHandler --&gt;
        ///        &lt;webSocketHandler&gt;BasicWebSocketHandler&lt;/webSocketHandler&gt;
        ///
        ///        &lt;!-- Supported database types (case insensitive): SQL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
    }
}
